"""
Builds the String Catalogs (English source + French) from the strings found in the Swift code:

    python scripts/build_strings.py

  ios/Parley/Resources/Localizable.xcstrings     app (+ Shared/ intents)
  ios/Parley/Resources/InfoPlist.xcstrings       microphone permission text, app name
  ios/ParleyWidgets/Localizable.xcstrings        Live Activity

Every entry is marked "manual" so Xcode never removes it. A key without a French translation stays in
English (and is listed at the end, so you can add it to FR below).
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import extract_strings  # noqa: E402

IOS = extract_strings.ROOT
SKIP = {"-", "·", "— ", "Parley"}

FR = {
    "%@ %@. Cancel anytime.": "%1$@ %2$@. Résiliable à tout moment.",
    "%@ left": "%@ restantes",
    "%@/month": "%@/mois",
    "%lld corrections applied": "%lld corrections appliquées",
    "%lld h of transcription per month": "%lld h de transcription par mois",
    "(recovered)": "(récupéré)",
    "A clean transcript with each speaker identified. Rename them in one tap, jump to any moment.":
        "Une transcription propre, chaque intervenant identifié. Renommez-les d'un geste, sautez à n'importe quel moment.",
    "About": "À propos",
    "Action items": "Actions à mener",
    "Add a document": "Ajouter un document",
    "Agenda, slides, notes (PDF, Word, PowerPoint, Excel, text). Used only to get names and terms right, then deleted from the server.":
        "Ordre du jour, présentation, notes (PDF, Word, PowerPoint, Excel, texte). Servent uniquement à bien orthographier noms et termes, puis sont supprimés du serveur.",
    "Allow microphone access in Settings to record.": "Autorisez l'accès au micro dans Réglages pour enregistrer.",
    "Allow the microphone": "Autoriser le micro",
    "Applies to the whole transcript and to exports.": "S'applique à toute la transcription et aux exports.",
    "Audio deleted from our servers after processing": "Audio supprimé de nos serveurs après traitement",
    "Audio is deleted from the server as soon as it is transcribed, and the transcript as soon as this iPhone has downloaded it. Recordings you do not transcribe never leave your iPhone.":
        "L'audio est supprimé du serveur dès qu'il est transcrit, et la transcription dès que cet iPhone l'a récupérée. Les enregistrements que vous ne transcrivez pas ne quittent jamais votre iPhone.",
    "Audio, transcripts and summaries on this iPhone. This cannot be undone.":
        "Audios, transcriptions et résumés sur cet iPhone. Action irréversible.",
    "Back 15 seconds": "Reculer de 15 secondes",
    "Best value": "Meilleure offre",
    "Cancel": "Annuler",
    "Change plan": "Changer de formule",
    "Choose it for strong accents or unusual languages: it avoids passages coming out translated.":
        "À préciser en cas d'accent marqué ou de langue moins courante : évite que des passages sortent traduits.",
    "Choose your plan": "Choisissez votre formule",
    "Close": "Fermer",
    "Continue": "Continuer",
    "Copy the summary": "Copier le résumé",
    "Copy the transcript": "Copier la transcription",
    "Correcting names and terms": "Correction des noms et termes",
    "Could not read this file (%@).": "Impossible de lire ce fichier (%@).",
    "Daily limit reached. Try again tomorrow.": "Limite quotidienne atteinte. Réessayez demain.",
    "Delete": "Supprimer",
    "Delete all recordings on this iPhone": "Supprimer tous les enregistrements de cet iPhone",
    "Delete all recordings?": "Supprimer tous les enregistrements ?",
    "Delete everything": "Tout supprimer",
    "Delete my data from the server": "Supprimer mes données du serveur",
    "Delete this recording?": "Supprimer cet enregistrement ?",
    "Delete your data from the server?": "Supprimer vos données du serveur ?",
    "Detect automatically": "Détection automatique",
    "Done": "OK",
    "Download": "Télécharger",
    "Essential": "Essentiel",
    "Every meeting, transcribed and summarized. Who said what, decisions, next steps.":
        "Chaque réunion transcrite et résumée. Qui a dit quoi, les décisions, les prochaines étapes.",
    "Expected names and terms": "Noms et termes attendus",
    "Export failed": "Échec de l'export",
    "Fixes names and jargon using your documents": "Corrige noms et jargon grâce à vos documents",
    "Follow playback": "Suivre la lecture",
    "Forward 15 seconds": "Avancer de 15 secondes",
    "Free for 7 days (%lld min of transcription), then %@ %@. Cancel anytime.":
        "Gratuit 7 jours (%1$lld min de transcription), puis %2$@ %3$@. Résiliable à tout moment.",
    "Free trial": "Essai gratuit",
    "Generated by AI from the recording. Check names, figures and quotes before sharing.":
        "Généré par IA à partir de l'enregistrement. Vérifiez noms, chiffres et citations avant de partager.",
    "Generated by Parley from an automatic transcript. Check names, figures and quotes before sharing.":
        "Généré par Parley à partir d'une transcription automatique. Vérifiez noms, chiffres et citations avant de partager.",
    "Get the full transcript, who said what, a summary and the action items.":
        "Obtenez la transcription complète, qui a dit quoi, un résumé et les actions à mener.",
    "Help and contact": "Aide et contact",
    "Identifies who is speaking": "Identifie qui parle",
    "Identify speakers": "Identifier les intervenants",
    "Identifying speakers": "Identification des intervenants",
    "Import an audio or video file": "Importer un fichier audio ou vidéo",
    "Importing…": "Importation…",
    "Keep the screen on while recording": "Garder l'écran allumé pendant l'enregistrement",
    "Key points, decisions and action items. Export to PDF, Notion or your notes.":
        "Points clés, décisions et actions. Export en PDF, vers Notion ou vos notes.",
    "Let participants know they are being recorded.": "Prévenez les participants qu'ils sont enregistrés.",
    "Manage subscription": "Gérer l'abonnement",
    "Mark": "Repère",
    "Mark this moment": "Marquer ce moment",
    "Markdown (Notion, Obsidian…)": "Markdown (Notion, Obsidian…)",
    "Microphone access": "Accès au micro",
    "Minimize": "Réduire",
    "Minutes renew %@": "Minutes renouvelées le %@",
    "Monthly": "Mensuel",
    "More": "Plus",
    "More time": "Plus de temps",
    "Name": "Nom",
    "Names, acronyms, jargon…": "Noms, acronymes, jargon…",
    "No active subscription found for this Apple ID.": "Aucun abonnement actif pour cet identifiant Apple.",
    "No connection to the server. Check your network and try again.":
        "Pas de connexion au serveur. Vérifiez votre réseau et réessayez.",
    "No match.": "Aucun résultat.",
    "No subscription": "Sans abonnement",
    "No summary": "Pas de résumé",
    "Not enough time left this month for this recording.": "Pas assez de temps restant ce mois-ci pour cet enregistrement.",
    "Not enough transcription time left (%@ remaining).": "Temps de transcription insuffisant (%@ restantes).",
    "Not now": "Plus tard",
    "OK": "OK",
    "Open Settings": "Ouvrir Réglages",
    "PDF document": "Document PDF",
    "Parley needs access to the microphone to record.": "Parley a besoin du micro pour enregistrer.",
    "Part of the speaker version may have been translated. The plain text is the reference.":
        "Une partie de la version par intervenant a peut-être été traduite. Le texte brut fait foi.",
    "Pause": "Pause",
    "Pause or resume recording": "Mettre en pause ou reprendre",
    "Paused": "En pause",
    "Paused by a call — resumes automatically": "En pause pendant l'appel — reprise automatique",
    "Payment is charged to your Apple ID at the end of the free trial, or at confirmation if no trial applies. The subscription renews automatically unless cancelled at least 24 hours before the end of the current period. Manage or cancel it in your App Store account settings.":
        "Le paiement est débité sur votre identifiant Apple à la fin de l'essai gratuit, ou à la confirmation en l'absence d'essai. L'abonnement se renouvelle automatiquement sauf résiliation au moins 24 heures avant la fin de la période en cours. Gérez-le ou résiliez-le dans les réglages de votre compte App Store.",
    "Plain text": "Texte brut",
    "Play": "Lire",
    "Play from %@": "Lire à partir de %@",
    "Preparing": "Préparation",
    "Privacy": "Confidentialité",
    "Privacy policy": "Politique de confidentialité",
    "Rate Parley": "Noter Parley",
    "Ready to transcribe": "Prêt à transcrire",
    "Record": "Enregistrer",
    "Record, even locked": "Enregistrez, même verrouillé",
    "Recording": "Enregistrement",
    "Recording continues with the screen locked either way.": "L'enregistrement continue écran verrouillé dans tous les cas.",
    "Recording deleted": "Enregistrement supprimé",
    "Recording in progress…": "Enregistrement en cours…",
    "Recording of %@": "Enregistrement du %@",
    "Recording — you can lock your iPhone": "Enregistrement — vous pouvez verrouiller l'iPhone",
    "Records with the screen locked, for hours": "Enregistre écran verrouillé, pendant des heures",
    "Reference documents": "Documents de référence",
    "Rename": "Renommer",
    "Rename %@": "Renommer %@",
    "Rename speaker": "Renommer l'intervenant",
    "Renews %@": "Renouvellement le %@",
    "Restore purchases": "Restaurer les achats",
    "Restoring…": "Restauration…",
    "Results": "Résultats",
    "Resume": "Reprendre",
    "Retrying…": "Nouvelle tentative…",
    "Same as the recording": "Celle de l'enregistrement",
    "Save": "Enregistrer",
    "Saving the audio…": "Enregistrement de l'audio…",
    "Search the transcript": "Rechercher dans la transcription",
    "Search titles and transcripts": "Rechercher titres et transcriptions",
    "See plans": "Voir les formules",
    "Sending the audio": "Envoi de l'audio",
    "Separated by commas. Helps spell people, products and jargon correctly.":
        "Séparés par des virgules. Aide à bien orthographier personnes, produits et jargon.",
    "Session expired. Try again.": "Session expirée. Réessayez.",
    "Settings": "Réglages",
    "Share": "Partager",
    "Share the audio": "Partager l'audio",
    "Smart correction": "Correction intelligente",
    "Smart correction could not run on this transcript.": "La correction intelligente n'a pas pu s'appliquer à cette transcription.",
    "Some passages came out in another alphabet. Choose the spoken language and transcribe again.":
        "Certains passages sont sortis dans un autre alphabet. Choisissez la langue parlée et relancez.",
    "Something went wrong.": "Un problème est survenu.",
    "Speaker %@": "Intervenant %@",
    "Speaker labels may change between parts of this long recording.":
        "Les intervenants peuvent changer de libellé entre les parties de ce long enregistrement.",
    "Spoken language": "Langue parlée",
    "Start": "Lancer",
    "Start Parley and put your iPhone down. It keeps recording with the screen locked, through calls and for hours.":
        "Lancez Parley et posez votre iPhone. Il continue d'enregistrer écran verrouillé, même après un appel, pendant des heures.",
    "Start my 7-day free trial": "Commencer mon essai gratuit de 7 jours",
    "Start my free trial": "Commencer mon essai gratuit",
    "Start recording": "Démarrer un enregistrement",
    "Start the 7-day free trial": "Commencer l'essai gratuit de 7 jours",
    "Start your free trial or subscribe to transcribe.": "Commencez l'essai gratuit ou abonnez-vous pour transcrire.",
    "Starts a new recording in Parley.": "Démarre un nouvel enregistrement dans Parley.",
    "Starts recording. Recording continues when the screen is locked.":
        "Démarre l'enregistrement. Il continue quand l'écran est verrouillé.",
    "Stop": "Arrêter",
    "Stop and save": "Arrêter et enregistrer",
    "Stop recording": "Arrêter l'enregistrement",
    "Subscribe": "S'abonner",
    "Subscription": "Abonnement",
    "Subtitles (SRT)": "Sous-titres (SRT)",
    "Summary": "Résumé",
    "Summary and action items": "Résumé et actions à mener",
    "Summary and action items in seconds": "Résumé et actions en quelques secondes",
    "Summary language": "Langue du résumé",
    "Tap the button to record. You can lock your iPhone: Parley keeps listening. You get the transcript, who said what, and a summary.":
        "Touchez le bouton pour enregistrer. Vous pouvez verrouiller l'iPhone : Parley continue d'écouter. Vous obtenez la transcription, qui a dit quoi, et un résumé.",
    "Terms": "Conditions",
    "Terms of use": "Conditions d'utilisation",
    "Text": "Texte",
    "The audio and its transcript will be deleted from this iPhone.": "L'audio et sa transcription seront supprimés de cet iPhone.",
    "The audio system restarted. Your recording was saved.": "Le système audio a redémarré. Votre enregistrement a été sauvegardé.",
    "The plans could not be loaded. Check your connection.": "Impossible de charger les formules. Vérifiez votre connexion.",
    "The recording could not start. Close other apps using the microphone and try again.":
        "L'enregistrement n'a pas pu démarrer. Fermez les autres apps qui utilisent le micro et réessayez.",
    "The recording is too short to transcribe.": "L'enregistrement est trop court pour être transcrit.",
    "The reference documents could not be read.": "Les documents de référence n'ont pas pu être lus.",
    "The service is busy. Try again in a minute.": "Le service est saturé. Réessayez dans une minute.",
    "The summary could not be generated. Transcribe again to retry.": "Le résumé n'a pas pu être généré. Relancez la transcription pour réessayer.",
    "The summary was turned off for this recording. The transcript is in the other tab.":
        "Le résumé était désactivé pour cet enregistrement. La transcription est dans l'autre onglet.",
    "The summary, ready to share": "Le résumé, prêt à partager",
    "The transcript is ready on the server but not yet downloaded.": "La transcription est prête sur le serveur mais pas encore téléchargée.",
    "The transcription service is temporarily unavailable. Your recording is safe: try again later.":
        "Le service de transcription est momentanément indisponible. Votre enregistrement est en sécurité : réessayez plus tard.",
    "The upload needs to be sent again.": "L'envoi doit être recommencé.",
    "The upload was interrupted (%@).": "L'envoi a été interrompu (%@).",
    "This file contains no audio.": "Ce fichier ne contient pas d'audio.",
    "This file could not be read as audio.": "Ce fichier n'a pas pu être lu comme un audio.",
    "This file is too large to upload.": "Ce fichier est trop volumineux pour être envoyé.",
    "This recording is longer than your plan allows per file (%@).": "Cet enregistrement dépasse la durée autorisée par fichier dans votre formule (%@).",
    "This transcription is no longer available on the server. Transcribe again.": "Cette transcription n'est plus disponible sur le serveur. Relancez-la.",
    "This week": "Cette semaine",
    "Title": "Titre",
    "To transcribe": "À transcrire",
    "Today": "Aujourd'hui",
    "Transcribe": "Transcrire",
    "Transcribe again": "Transcrire à nouveau",
    "Transcribe automatically after recording": "Transcrire automatiquement après l'enregistrement",
    "Transcribing": "Transcription",
    "Transcript": "Transcription",
    "Transcript, speakers and AI summary": "Transcription, intervenants et résumé IA",
    "Transcription": "Transcription",
    "Transcription defaults": "Transcription par défaut",
    "Transcription interrupted": "Transcription interrompue",
    "Transcription time": "Temps de transcription",
    "Transcriptions in progress are cancelled. Recordings on this iPhone are kept.":
        "Les transcriptions en cours sont annulées. Les enregistrements de cet iPhone sont conservés.",
    "Trial ends %@": "Fin de l'essai le %@",
    "Try Parley free for 7 days": "Essayez Parley gratuitement 7 jours",
    "Try again": "Réessayer",
    "Two transcriptions are already running. Try again when one finishes.": "Deux transcriptions sont déjà en cours. Réessayez quand l'une d'elles sera terminée.",
    "Unexpected answer from the server.": "Réponse inattendue du serveur.",
    "Unlock transcription": "Débloquer la transcription",
    "Use these settings by default": "Utiliser ces réglages par défaut",
    "Uses %@ of your %@ left": "Utilise %1$@ sur vos %2$@ restantes",
    "Version": "Version",
    "Very little speech was detected. Was the microphone covered or far from the speakers?":
        "Très peu de parole détectée. Le micro était-il couvert ou loin des intervenants ?",
    "View": "Affichage",
    "Who said what": "Qui a dit quoi",
    "Working on it…": "Traitement en cours…",
    "Writing the summary": "Rédaction du résumé",
    "Yearly": "Annuel",
    "Yesterday": "Hier",
    "You can close Parley: you will get a notification when it is ready.": "Vous pouvez fermer Parley : une notification vous préviendra quand ce sera prêt.",
    "Your data was deleted from the server. Your subscription is not affected.": "Vos données ont été supprimées du serveur. Votre abonnement n'est pas affecté.",
    "Your first meeting starts here": "Votre première réunion commence ici",
    "Your iPhone is almost full. Free up some space to record.": "Votre iPhone est presque plein. Libérez de l'espace pour enregistrer.",
    "Your plan transcribes up to %@ per recording.": "Votre formule transcrit jusqu'à %@ par enregistrement.",
    "Your purchase is waiting for approval.": "Votre achat est en attente d'approbation.",
    "Your recording is safe on this iPhone.": "Votre enregistrement est en sécurité sur cet iPhone.",
    "Your subscription is active but the server cannot be reached right now.": "Votre abonnement est actif mais le serveur est injoignable pour le moment.",
    "per month": "par mois",
    "per year": "par an",
    "Your subscription could not be verified by the server. Try Restore purchases; if it persists, contact support.":
        "Votre abonnement n'a pas pu être vérifié par le serveur. Essayez « Restaurer les achats » ; si le problème persiste, contactez l'assistance.",
    "Your purchase went through, but the server has not confirmed it yet. Try Restore purchases in a moment.":
        "Votre achat est validé, mais le serveur ne l'a pas encore confirmé. Essayez « Restaurer les achats » dans un instant.",
    # Live Activity
    "Parley is recording": "Parley enregistre",
}

INFO_PLIST = {
    "NSMicrophoneUsageDescription": (
        "Parley records your meetings so it can transcribe and summarize them.",
        "Parley enregistre vos réunions pour les transcrire et les résumer."),
    "CFBundleDisplayName": ("Parley", "Parley"),
}


def unit(value):
    return {"stringUnit": {"state": "translated", "value": value}}


def catalog(entries):
    """entries: {key: (en, fr or None)}"""
    strings = {}
    for key in sorted(entries):
        en, fr = entries[key]
        loc = {"en": unit(en)}
        if fr:
            loc["fr"] = unit(fr)
        strings[key] = {"extractionState": "manual", "localizations": loc}
    return {"sourceLanguage": "en", "strings": strings, "version": "1.0"}


def write(path, data):
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(data, fh, ensure_ascii=False, indent=2, separators=(",", " : "))
        fh.write("\n")
    print("wrote", os.path.relpath(path, os.path.join(IOS, "..")), "(%d keys)" % len(data["strings"]))


def main():
    missing = []
    for targets, out in ((["Parley", "Shared"], os.path.join(IOS, "Parley", "Resources", "Localizable.xcstrings")),
                         (["ParleyWidgets"], os.path.join(IOS, "ParleyWidgets", "Localizable.xcstrings"))):
        keys = [k for k in extract_strings.keys_for(targets) if k not in SKIP]
        entries = {}
        for k in keys:
            entries[k] = (k, FR.get(k))
            if k not in FR:
                missing.append(k)
        write(out, catalog(entries))
    write(os.path.join(IOS, "Parley", "Resources", "InfoPlist.xcstrings"), catalog(INFO_PLIST))
    if missing:
        print("\nNo French translation yet for:")
        for k in sorted(set(missing)):
            print("  ", repr(k))


if __name__ == "__main__":
    main()
