import SwiftUI

struct SummaryView: View {
    let rec: Recording
    let result: TranscriptResult
    @Environment(RecordingStore.self) private var store

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            ForEach(result.warnings, id: \.self) { w in
                if let text = Self.warningText(w) {
                    Label(text, systemImage: "exclamationmark.triangle")
                        .font(.footnote)
                        .foregroundStyle(.orange)
                        .card()
                }
            }

            if let s = result.summary {
                if !s.subtitle.isEmpty {
                    Text(s.subtitle)
                        .font(.subheadline)
                        .italic()
                        .foregroundStyle(.secondary)
                }
                if let actions = s.actions, !actions.isEmpty {
                    actionsCard(actions)
                }
                ForEach(Array(s.sections.enumerated()), id: \.offset) { _, sec in
                    VStack(alignment: .leading, spacing: 10) {
                        Text(sec.head)
                            .font(.headline)
                            .foregroundStyle(Theme.indigo)
                        ForEach(Array(sec.bullets.enumerated()), id: \.offset) { _, b in
                            HStack(alignment: .firstTextBaseline, spacing: 10) {
                                Circle().fill(Theme.violet).frame(width: 6, height: 6)
                                    .alignmentGuide(.firstTextBaseline) { $0[VerticalAlignment.center] + 4 }
                                Text(b).textSelection(.enabled)
                            }
                        }
                    }
                    .card()
                }
            } else {
                ContentUnavailableView("No summary", systemImage: "text.alignleft",
                                       description: Text("The summary was turned off for this recording. The transcript is in the other tab."))
            }

            if !result.corrections.isEmpty {
                DisclosureGroup {
                    VStack(alignment: .leading, spacing: 6) {
                        ForEach(Array(result.corrections.enumerated()), id: \.offset) { _, c in
                            HStack(alignment: .firstTextBaseline) {
                                Text(c.from).strikethrough().foregroundStyle(.secondary)
                                Image(systemName: "arrow.right").font(.caption2)
                                Text(c.to).fontWeight(.medium)
                                if !c.why.isEmpty {
                                    Text("— " + c.why).font(.caption).foregroundStyle(.secondary)
                                }
                            }
                            .font(.subheadline)
                        }
                    }
                    .padding(.top, 6)
                } label: {
                    Label(tr("%lld corrections applied", result.corrections.count), systemImage: "wand.and.stars")
                        .font(.subheadline.weight(.medium))
                }
                .card()
            }

            Text("Generated by AI from the recording. Check names, figures and quotes before sharing.")
                .font(.caption)
                .foregroundStyle(.secondary)
                .padding(.top, 4)
        }
    }

    private func actionsCard(_ actions: [ActionItem]) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            Label("Action items", systemImage: "checklist")
                .font(.headline)
                .foregroundStyle(Theme.indigo)
            ForEach(Array(actions.enumerated()), id: \.offset) { i, a in
                let done = rec.doneActions.contains(i)
                Button {
                    store.update(rec.id) { r in
                        if r.doneActions.contains(i) { r.doneActions.remove(i) } else { r.doneActions.insert(i) }
                    }
                } label: {
                    HStack(alignment: .firstTextBaseline, spacing: 12) {
                        Image(systemName: done ? "checkmark.circle.fill" : "circle")
                            .foregroundStyle(done ? .green : Theme.indigo)
                            .font(.title3)
                        VStack(alignment: .leading, spacing: 3) {
                            Text(a.task)
                                .strikethrough(done)
                                .foregroundStyle(done ? .secondary : .primary)
                                .multilineTextAlignment(.leading)
                            let meta = [a.owner, a.due].filter { !$0.isEmpty }
                            if !meta.isEmpty {
                                Text(meta.joined(separator: " · "))
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                    }
                }
                .buttonStyle(.plain)
                .sensoryFeedback(.selection, trigger: done)
            }
        }
        .card()
    }

    static func warningText(_ code: String) -> String? {
        switch code {
        case "low_speech": return tr("Very little speech was detected. Was the microphone covered or far from the speakers?")
        case "foreign_script": return tr("Some passages came out in another alphabet. Choose the spoken language and transcribe again.")
        case "speaker_language": return tr("Part of the speaker version may have been translated. The plain text is the reference.")
        case "speakers_not_anchored": return tr("Speaker labels may change between parts of this long recording.")
        case "correction_failed": return tr("Smart correction could not run on this transcript.")
        case "summary_failed": return tr("The summary could not be generated. Transcribe again to retry.")
        case "docs_unreadable": return tr("The reference documents could not be read.")
        default: return nil
        }
    }
}
